# permissions for end users to view connections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connection-viewer-role
rules:
- apiGroups:
  - etl.dataworkz.nl
  resources:
  - connections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etl.dataworkz.nl
  resources:
  - connections/status
  verbs:
  - get
