
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - etl.dataworkz.nl
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etl.dataworkz.nl
  resources:
  - datasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - etl.dataworkz.nl
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etl.dataworkz.nl.dataworkz.nl
  resources:
  - cronworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etl.dataworkz.nl.dataworkz.nl
  resources:
  - cronworkflows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - etl.dataworkz.nl.dataworkz.nl
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etl.dataworkz.nl.dataworkz.nl
  resources:
  - workflows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - etl.dataworkz.nl.dataworkz.nl
  resources:
  - workflowtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etl.dataworkz.nl.dataworkz.nl
  resources:
  - workflowtemplates/status
  verbs:
  - get
  - patch
  - update
