apiVersion: etl.dataworkz.nl/v1alpha1
kind: DataSet
metadata:
  name: sessions-dataset
spec:
  type: mysql
  storageType: Persistent
  connection:
    connectionFrom:
      name: mysql-connection
  metadata:
    host:
      value: mysql
    port:
      value: "3000"
    database:
      value: mydatabase
    
