name: lint-and-test
on:
  push:
    branches-ignore:
      - 'releases/**'
      - 'main'
jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  test:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2
      - name: Setup Ginkgo
        run: go get github.com/onsi/ginkgo/ginkgo
      - name: Install Kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1.2
        with:
          version: 2.3.1
      - name: Run Tests
        run: make test
