name: review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"

      - name: setup kubebuilder 
        uses: RyanSiu1995/kubebuilder-action@v1.2
        with:
          version: 3.0.0
          

      - name: test
        run: make test

