name: review

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"

      - name: setup kubebuilder 
        run: |
          curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)
          sudo chmod +x kubebuilder && sudo mv kubebuilder /usr/local/bin/

      - name: build & test
        run: make docker-build

